project:
  id: my-ai-system-20260215-023345
  name: My AI System
  description: null
  created_at: '2026-02-15T02:33:45.848887+00:00'
  updated_at: '2026-02-15T02:33:55.484071+00:00'
inputs:
  industry_id: finance
  segment_id: banking
  use_case_id: fraud-detection
  selected_packs:
  - domain: governance
    pack_id: eu-ai-act
    version: 2024-1689
  - domain: safety
    pack_id: model-documentation
    version: '1.0'
  - domain: security
    pack_id: owasp-llm-top10
    version: '1.1'
  scope_answers: &id002
    materially_influences_decisions: true
    processes_pci: true
    customer_facing: false
    jurisdictions: &id001
    - US
context:
  system:
    name: My AI System
  industry:
    id: finance
  segment:
    id: banking
  use_case:
    id: fraud-detection
  tags:
  - ml
  - classifier
  - decision_support
  - finance
  - pii
  pattern:
    rag: false
    agentic: false
    chatbot: false
    classifier: true
    decision_support: true
  data:
    phi: false
    pii: true
    pci: true
  deployment:
    internet_exposed: false
    customer_facing: false
  jurisdiction:
    list: *id001
    eu: false
    us: true
    uk: false
  model:
    sourcing: unknown
    fine_tuned: false
  scope: *id002
generated:
  generator_version: 0.1.0
  taxonomy_hash: 9538004338626b800551ab7d87dee4a65d0171737e477a58de90d405cb2dedef
  packs_hash: 7e6c2ef56fe1c8d491c42d9cfccc4fbf6e464b1ac5cbfb96242c485f66142efb
  checklist_hash: e92b90eef3fd36d4a3119c38f391b22db2bc769f8f1010aff36c978de4775a99
