project:
  id: my-ai-system-20260215-024444
  name: My AI System
  description: null
  created_at: '2026-02-15T02:44:44.225595+00:00'
  updated_at: '2026-02-15T02:44:44.225605+00:00'
inputs:
  industry_id: healthcare
  segment_id: payer
  use_case_id: claims-approval-assistant
  selected_packs:
  - domain: governance
    pack_id: eu-ai-act
    version: 2024-1689
  - domain: safety
    pack_id: model-documentation
    version: '1.0'
  scope_answers: &id002
    materially_influences_decisions: true
    processes_phi: true
    uses_tools: false
    internet_exposed: false
    jurisdictions: &id001
    - US
    model_sourcing: api
context:
  system:
    name: My AI System
  industry:
    id: healthcare
  segment:
    id: payer
  use_case:
    id: claims-approval-assistant
  tags:
  - llm
  - decision_support
  - healthcare
  - payer
  - phi
  - pii
  - rag
  pattern:
    rag: true
    agentic: false
    chatbot: false
    classifier: false
    decision_support: true
  data:
    phi: true
    pii: true
    pci: false
  deployment:
    internet_exposed: false
    customer_facing: false
  jurisdiction:
    list: *id001
    eu: false
    us: true
    uk: false
  model:
    sourcing: api
    fine_tuned: false
  scope: *id002
generated:
  generator_version: 0.1.0
  taxonomy_hash: 9538004338626b800551ab7d87dee4a65d0171737e477a58de90d405cb2dedef
  packs_hash: 6ff9aaa5977f058189b72f798a8f5516d0d7d18abb4b57478e2288bacdce9abb
  checklist_hash: 62e4a2e4d602e0815eb8352de36bb2b8901b726f69189f6facd10f40a6519634
